name: CI runner

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'  
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
      - name: Lint
        run: |
          yarn lint
        env:
          CI: true
      - name: Build
        run: |
          sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              libssl-dev \
              appmenu-gtk3-module \
              libgtk-3-dev
          cargo install tauri-bundler --force
          yarn build
        env:
          CI: true
